# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rhighlightjs}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["romanvbabenko"]
  s.date = %q{2009-08-28}
  s.default_executable = %q{rhighlightjs}
  s.description = %q{Javascript syntax highlighter by Ivan Salagaev}
  s.email = %q{romanvbabenko@gmail.com}
  s.executables = ["rhighlightjs"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "assets/images/brown_papersq.png",
     "assets/images/brown_papersq.png",
     "assets/images/paperbg.gif",
     "assets/images/paperbg.gif",
     "assets/images/school_book.png",
     "assets/images/school_book.png",
     "assets/javascripts/highlight.js",
     "assets/javascripts/highlight.js",
     "assets/javascripts/highlight.pack.js",
     "assets/javascripts/highlight.pack.js",
     "assets/javascripts/languages/1c.js",
     "assets/javascripts/languages/1c.js",
     "assets/javascripts/languages/apache.js",
     "assets/javascripts/languages/apache.js",
     "assets/javascripts/languages/avrasm.js",
     "assets/javascripts/languages/avrasm.js",
     "assets/javascripts/languages/axapta.js",
     "assets/javascripts/languages/axapta.js",
     "assets/javascripts/languages/bash.js",
     "assets/javascripts/languages/bash.js",
     "assets/javascripts/languages/cpp.js",
     "assets/javascripts/languages/cpp.js",
     "assets/javascripts/languages/cs.js",
     "assets/javascripts/languages/cs.js",
     "assets/javascripts/languages/css.js",
     "assets/javascripts/languages/css.js",
     "assets/javascripts/languages/delphi.js",
     "assets/javascripts/languages/delphi.js",
     "assets/javascripts/languages/diff.js",
     "assets/javascripts/languages/diff.js",
     "assets/javascripts/languages/django.js",
     "assets/javascripts/languages/django.js",
     "assets/javascripts/languages/dos.js",
     "assets/javascripts/languages/dos.js",
     "assets/javascripts/languages/dynamic.js",
     "assets/javascripts/languages/dynamic.js",
     "assets/javascripts/languages/html-xml.js",
     "assets/javascripts/languages/html-xml.js",
     "assets/javascripts/languages/ini.js",
     "assets/javascripts/languages/ini.js",
     "assets/javascripts/languages/java.js",
     "assets/javascripts/languages/java.js",
     "assets/javascripts/languages/javascript.js",
     "assets/javascripts/languages/javascript.js",
     "assets/javascripts/languages/lisp.js",
     "assets/javascripts/languages/lisp.js",
     "assets/javascripts/languages/mel.js",
     "assets/javascripts/languages/mel.js",
     "assets/javascripts/languages/parser3.js",
     "assets/javascripts/languages/parser3.js",
     "assets/javascripts/languages/perl.js",
     "assets/javascripts/languages/perl.js",
     "assets/javascripts/languages/php.js",
     "assets/javascripts/languages/php.js",
     "assets/javascripts/languages/profile.js",
     "assets/javascripts/languages/profile.js",
     "assets/javascripts/languages/python.js",
     "assets/javascripts/languages/python.js",
     "assets/javascripts/languages/renderman.js",
     "assets/javascripts/languages/renderman.js",
     "assets/javascripts/languages/ruby.js",
     "assets/javascripts/languages/ruby.js",
     "assets/javascripts/languages/smalltalk.js",
     "assets/javascripts/languages/smalltalk.js",
     "assets/javascripts/languages/sql.js",
     "assets/javascripts/languages/sql.js",
     "assets/javascripts/languages/static.js",
     "assets/javascripts/languages/static.js",
     "assets/javascripts/languages/vbscript.js",
     "assets/javascripts/languages/vbscript.js",
     "assets/javascripts/languages/www.js",
     "assets/javascripts/languages/www.js",
     "assets/javascripts/styleswitch.js",
     "assets/javascripts/styleswitch.js",
     "assets/stylesheets/ascetic.css",
     "assets/stylesheets/ascetic.css",
     "assets/stylesheets/brown_paper.css",
     "assets/stylesheets/brown_paper.css",
     "assets/stylesheets/brown_papersq.png",
     "assets/stylesheets/brown_papersq.png",
     "assets/stylesheets/dark.css",
     "assets/stylesheets/dark.css",
     "assets/stylesheets/default.css",
     "assets/stylesheets/default.css",
     "assets/stylesheets/far.css",
     "assets/stylesheets/far.css",
     "assets/stylesheets/github.css",
     "assets/stylesheets/github.css",
     "assets/stylesheets/idea.css",
     "assets/stylesheets/idea.css",
     "assets/stylesheets/ir_black.css",
     "assets/stylesheets/ir_black.css",
     "assets/stylesheets/magula.css",
     "assets/stylesheets/magula.css",
     "assets/stylesheets/notebook.css",
     "assets/stylesheets/notebook.css",
     "assets/stylesheets/school_book.css",
     "assets/stylesheets/school_book.css",
     "assets/stylesheets/school_book.png",
     "assets/stylesheets/school_book.png",
     "assets/stylesheets/sunburst.css",
     "assets/stylesheets/sunburst.css",
     "assets/stylesheets/vs.css",
     "assets/stylesheets/vs.css",
     "assets/stylesheets/zenburn.css",
     "assets/stylesheets/zenburn.css",
     "assets/stylesheets/zenburn.css.txt",
     "assets/stylesheets/zenburn.css.txt",
     "bin/rhighlightjs",
     "init.rb",
     "install.rb",
     "lib/rhighlightjs.rb",
     "rhighlightjs.gemspec",
     "tasks/rhighlightjs_tasks.rake",
     "test/rhighlightjs_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/romanvbabenko/rhighlightjs}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.2}
  s.summary = %q{It is the helper for higlight.js}
  s.test_files = [
    "test/test_helper.rb",
     "test/rhighlightjs_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end
